---
title: "Executive Summary"
author: Hnin Thuzar Lwin & Wai Linn
format: gfm
---

# Executive Summary 

## An analysis of contraceptive knowledge, practice and unmet need among currently married women aged 15-49 based on demographic characteristics in Myanmar 

## Background

Sufficient knowledge of contraceptive methods, contraceptive utilization and reduction of unmet need are crucial to reducing unintended and unwanted pregnancies and abortions. Many studies show that socio-demographic characteristics influence contraceptive usage among reproductive-aged women in developing countries. Our project iss designed to assess the differences of contraceptive knowledge, practice and unmet need and their associations among currently married women aged 15-49 according to demographic characteristics in Myanmar. 

Myanmar, located in Southeast Asia, consists of 7 states, 7 regions, and 1 union territory. The different terms “state” and “region” are intentionally used in Myanmar to differentiate the geographical locations between one dominant ethnic population, which is Bamar, with the majority residing in the regions and other ethnic minority populations typically inhabiting the states. Since 1962, certain regions such as Chin, Kachin, Kayin, and Rakhine states have experienced significant armed conflicts between pro-Bamar government military forces and ethnic armed groups. Consequently, these conflict-affected areas lag behind in terms of development, facing disparities, for instance, access to healthcare, and education compared to their non-conflicted counterparts. Specifically focusing on healthcare, significant disparities exist in health service accessibility across different ethnic populations, influenced by various demographic characteristics, including conflict-affected situations. However, there is limited data-driven evidence to quantify the extent of these disparities at the state/region level. To address this gap, we conduct an analysis using a nationally representative dataset to examine the associations between demographic characteristics and family planning service accessibility inequities in Myanmar. Our objective is to provide vital insights to policymakers, implementation partners, and donors, empowering them to tailor strategic and targeted family planning services to communities most in need.

## Research Question

1. How do demographic characteristics influence contraceptive knowledge, practices and unmet need among currently married women aged 15-49 in Myanmar?
2. Is there any disparities in accessing contraceptive knowledge and practice, and unmet need between regions and states in Myanmar?

## Data Analysis 
For our research question, we use the Demographic and Health Surveys (DHS) dataset, conducted by the Ministry of Health and Sports (MoHS) in Myanmar in 2016. This survey employed stratified two-stage cluster sampling and weighted sample size calculation methods to ensure national representativeness and validity. The dataset encompassed a wide range of demographic and health-related information, including family planning practices among women aged 15-49. Among all the available datasets, we select the family planning dataset, which is an individual-level dataset that focuses specifically on family planning knowledge and practices of women aged 15-49, with a total of 12,885 participants. However, while information of contraceptive knowledge was collected for all reproductive-aged women regardless of marital status, the the survey only interviewed currently married women for their contraceptive practices. Therefore, we select currently married women as our sample population. This approach allows us for a more meaningful comparison of contraceptive knowledge, practices, and unmet needs. 

Our Key variables are as below:
- Demographic characteristics: age (5-yr group), location (region/state), residence (urban/rural), education, wealth index
- Outcome: contraceptive knowledge, practice, unmet need (Binary outcome: Yes/No)
To facilitate this analysis, we stratify exposure variables based on demographic features and research interests. Specifically, we change age as a continuous variable into categorical one with 5-year group. We also divide regional locations into states and regions, the type of residence into urban and rural areas, and education status into four levels - no education, primary education, secondary education, and higher education, wealth index into five levels - poorest, poorer, middle, richer, and richest. 

For the data analysis, we employ some data visualization tools to examine differences in contraceptive knowledge and practices among women based on demographic characteristics. We conduct comparisons for each demographic characteristic and further investigate the extent of changes by combining certain variables. We also compare the trend of contraceptive knowledge, practice and unmet need within groups between regions and states. Besides, we assess whether these characteristics are associated with contraceptive knowledge, practice and unmet needs by using regression models. Recognizing the importance of generalizability and representativeness, we incorporate sampling weight into our analysis. 

## Key Findings
### Contraceptive Knowledge
Women with higher education demonstrate a greater proportion of contraceptive knowledge compared to those with lower or no education. Among age groups, the youngest (15-19 years) exhibit the lowest proportion of contraceptive knowledge  (94%), particularly evident among younger women with no education (86%). Women in regions generally have equal or higher knowledge proportions compared to those in states across all wealth index groups, except for the richer group, where women in states show higher knowledge proportions. Urban residents consistently display higher contraceptive knowledge across all wealth index groups, except for the poorest group, where urban residents in states have lower knowledge proportions than rural residents. These findings underscore the variability in contraceptive knowledge among women, even within regions, influenced by residence and wealth. In combination of location, residence, and wealth index, relatively poor women in rural areas within states tend to have less contraceptive knowledge.  

### Contraceptive Practice

The proportion of contraceptive method usage generally increases with education levels and age until around 40 years, after which it tends to decline. Younger and older women with lower education levels tend to have lower usage of contraceptive methods. Regarding location, residence and wealth index, poorer women from state and rural are less likely to use contraceptive methods. In particular, women living in regions have a higher proportion of contraceptive practice compared to those living in states (53% and 43% respectively). Similarly, women living in urban were more likely to use contraceptive methods than those living in rural (60% and 50% respectively). Furthermore, the proportion of contraceptive usage increases with higher wealth index.

### Unmet Need

The proportion of unmet need decreases with higher education levels. Regarding age groups, women being in the older age group (40-44) and (45-49) have the highst proportion of unmet need (30% adn 47% respectively). Within age and education strata, younger and older women with lower education levels are more likely to experience unmet need. Additionally, the proportion of unmet need is lower among women living in regions (23%) compared to those in states (31%), with a similar pattern observed in urban and rural areas (18% and 26% respectively). Moreover, as the wealth index rises, the likelihood of unmet need decreases. When considering the combination of location, residence, and wealth, poorer women from rural areas within states are more likely to experience unmet need. 

### Comparison between Regions and States

In general, women residing in regions exhibit higher levels of knowledge and engagement with contraceptive methods, accompanied by reduced unmet needs compared to their counterparts in states. However, upon closer examination, significant disparities emerge within regions when considering various demographic factors such as age, education, residency, and socioeconomic status.

Even within regions, specific groups face pronounced challenges in accessing and utilizing contraceptive services effectively. For instance, women lacking formal education, residing in rural areas, belonging to the lowest wealth quintiles, or falling within the youngest (15-19) or oldest (45-49) age brackets demonstrate the lowest rates of contraceptive adoption and the highest unmet needs.

This highlights a concerning pattern where communities with these characteristics are often overlooked in terms of receiving quality contraceptive services and support. For example, the proportion of contraceptive utilization among women without formal education residing in regions hovers around 40%, underscoring the urgent need for targeted interventions to address these disparities and ensure equitable access to reproductive healthcare.   

In Myanmar, the most common contraceptive methods used are injection and pills (50.20% and 26.1% respectively).

### Regressions

These regression results indicate that while living in regions, living in urban, being in the age groups of 20-39, and having secondary education, being in the richer and richest wealth index group are associated with increased likelihoods of contraceptive use, those factors are associated with decreased likelihoods of unmet need.  


## Conclusions

The findings underscore disparities in accessing knowledge, practicing contraceptive methods, and experiencing unmet needs across various demographic characteristics and their combinations. For example, women residing in rural areas within specific regions tend to have lower levels of knowledge and practice regarding contraception, alongside higher rates of unmet needs compared to their counterparts in urban areas within states. Our findings were reinforced by the use of sampling weights, enhancing the representativeness of our analysis. However, several limitations exist. Firstly, certain confounding factors were not accounted for in our analysis. Secondly, due to data and time constraints, not all demographic characteristics could be included. Lastly, as the dataset dates back to 2016, our findings may not fully reflect the current situation. Nevertheless, our results remain valuable for informing policymakers, implementation partners, and donors, guiding strategic and targeted interventions. Additionally, they can serve as a basis for evaluating the effectiveness of ongoing reproductive health projects and contraceptive provision initiatives.  


*to add dashboard link if feasible* 

*to add references*
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9678470/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7837347/



